[package]
name = "bweb"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.11.0"
clap = { version = "4.5.39", features = ["derive"] }

[profile.release]
lto = true
strip = true
opt-level = 3
codegen-units = 1

